Allow system-wide installs to specify both a root_path and a user.
sous-chefs/ruby_rbenv pull request #248
Opened 2019-04-01 18:02 UTC by corporealfunk

### Description

Previously if a user was specified, the cookbook assumed a user rbenv installation and also ran scripts as that user. The only way to signal a system-wide install was to omit a user property for rbenv-* resources. This had unfortunate side effects, for example all script resources would be forced to run as root instead of a specific user.

Allowing one to pass a root_path property to resources that leverage rbenv-script or rbenv-plugin and others required adding a root_path property to almost all the resources.  Because we want to keep the lazy-loaded path DRY, it was necessary to refactor the root_path code into it's own module function (and not an module instance function since we need to call it during resource declaration).

This is not thoroughly tested, though the ubuntu-1804 tests as written pass, using kitchen verify.

I have not tested that specifying a root_path property on all resources results in the root_path property being utilized correctly.

### Issues Resolved

#247 

### Contribution Check List

- [ ] All tests pass.  (kitchen test *-ubuntu-1804 tests pass.)
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-04-01 18:02 UTC, kitchen-porter commented
<!--
  1 Error: Please include a <a href="http...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a <a href="https://github.com/sous-chefs/line-cookbook/blob/master/CHANGELOG.md">CHANGELOG</a> entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-04-04 08:38 UTC, damacus commented on resources/gem.rb
> +property :root_path,              String, default: lazy { Chef::Rbenv.root_path(node, user) }
I was wondering why you were using self above, but this is a really smart pattern. I think we should adopt this across the board.

2019-04-04 08:39 UTC, damacus commented
If you can add a CHANGELOG for this I'll squash and merge, and release it.

As noted, the use of self and the namespace is really smart. I think to avoid name collisions we should be using that type of notation in more places.

2019-08-09 12:48 UTC, damacus requested changes
Needs a, changelog as per the bots request.

2019-09-30 13:57 UTC, closed without merging