Always use latest 2 orb
sous-chefs/ruby_rbenv pull request #256
Opened 2019-08-02 07:28 UTC by Xorima

2019-08-02 07:28 UTC, damacus submitted a review, later dismissed

2019-08-06 14:36 UTC, damacus requested changes
Deprecation

2019-08-06 14:36 UTC, damacus commented on kitchen.dokken.yml
> +      image: dokken/debian-8
Debian 8 is deprecated

2019-08-07 07:50 UTC, kitchen-porter commented
<!--
  0 Errors
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2019-08-07 11:57 UTC, Xorima commented
libssl-dev required for these servers not libssl-dev1.0

2019-08-08 07:24 UTC, Xorima commented
@damacus lgtm, separate project to support deb 10 as it just breaks everything currently (no java, some packages just don't exist etc)

2019-08-08 07:25 UTC, damacus approved these changes

2019-08-08 07:26 UTC, merged