Namespace the run_state variable
sous-chefs/ruby_rbenv pull request #287
Opened 2020-06-20 17:36 UTC by petracvv

Signed-off-by: Mihai Petracovici <petracvv@users.noreply.github.com>

# Description
This namespaces the run_state variables used internally by the cookbook to avoid conflicts with other cookbooks.

## Issues Resolved

#285 

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

2020-06-20 17:41 UTC, petracvv commented
Looks like tests are failing because the unit tests are not in a spec directory. Is that something I should fix?

2020-06-24 21:40 UTC, damacus commented on libraries/helpers.rb
> +          node.run_state['sous-chefs']['ruby_rbenv']['root_path'][resource_user]
```suggestion
          node.run_state['ruby_rbenv']['root_path'][resource_user]
```

Just using ruby_rbenv is probably enough here considering we have the `ruby_rbenv` namespace on supermarket

2020-06-24 21:40 UTC, damacus requested changes
Just using ruby_rbenv is probably enough here considering we have the ruby_rbenv namespace on supermarket

2020-07-15 17:26 UTC, petracvv commented
I think to be consistent with the pyenv cookbook, we should leave it under the sous-chefs namespace (see sous-chefs/pyenv#70)

2020-08-19 22:15 UTC, kitchen-porter commented
<!--
  1 Error: Please include a CHANGELOG ent...
  1 Warning: This Pull Request is probably ...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">This Pull Request is probably missing tests.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2020-11-23 18:20 UTC, Xorima commented
Hey @petracvv 

Can we get a changelog entry so this can be shipped please?

Thanks

2020-11-26 08:24 UTC, merged

2020-11-26 08:24 UTC, kitchen-porter commented
Released as: [3.0.0](https://github.com/sous-chefs/ruby_rbenv/releases/tag/3.0.0)

2020-12-01 23:35 UTC, petracvv commented
Thanks for the merge! Sorry about taking so long to finish this